apiVersion: v2
appVersion: "0.14"
description: A Helm chart for imagepullsecret-patcher
home: https://github.com/titansoft-pte-ltd/imagepullsecret-patcher
maintainers:
- email: ops@empathy.co
  name: Empathy Platform Team
name: imagepullsecret-patcher
sources:
- https://github.com/titansoft-pte-ltd/imagepullsecret-patcher
type: application
version: 0.1.1
